name:        lira
version:     0.2.0.0

synopsis:    'Declarative financial contract language'
description: 'Lira is a declarative domain-specific language designed to be the backbone of financial contracts that can be executed on the blockchain'
category:    Ethereum, Finance, Network, Language
license:     MIT

homepage:    https://github.com/etoroxlabs/lira
author:      Thorkil Vaerge, Mads Gram, Simon Shine, Peter Emil Jensen
maintainer:  shreddedglory@gmail.com
copyright:   2020 eToroX Labs

library:
  source-dirs: src
  dependencies:
    - base >= 4.9.1.0
    - mtl
    - parsec
    - text
    - bytestring >= 0.10.8.1
    - containers >= 0.5.7.1
    - cryptonite >= 0.21
    - aeson >= 1.0.2.1
    - split >= 0.2.3.1
    - directory >= 1.3.0.0

executables:
  lirac: &lirac
    main: src/Main.hs
    dependencies:
      - lira
      - base >= 4.9.1.0
      - aeson >= 1.0.2.1
      - bytestring >= 0.10.8.1
      - split >= 0.2.3.1
      - directory >= 1.3.0.0

tests:
  unit:
    source-dirs: unittests
    main: main_tests.hs
    dependencies:
      - lira
      - base >= 4.9.1.0
      - HUnit
      - QuickCheck
      - containers
      - hspec
      - mtl
